# src: https://docs.astral.sh/uv/guides/integration/docker/#developing-in-a-container

services:
  api:
    build:
      context: ./backend
      target: test
    ports:
      - 8000:8000
    command: pytest -x
    depends_on:
      - db

  db:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"