name: Style & Test Checks
on:
  pull_request:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MONGO_URI: "mongodb://db:27017/"
  MONGO_TEST_URI: "mongodb://db:27017/"

jobs:
  # src: https://akhilaariyachandra.com/blog/prettier-in-github-actions
  frontend-checks:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run frontend checks
        run: |
                cd frontend
                npm ci
                npm run lint
                npm run test
  backend-checks:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      #  Not needed since compose.test.yml setups up mongodb
      # - name: MongoDB in GitHub Actions
      #   uses: supercharge/mongodb-github-action@1.11.0      
      - name: Run backend checks
        run: make workflow-test
